apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: demo-deployment
  ports:
    - port: 80
      targetPort: 80
