namespace: kowabunga-monitoring
domain: tortueninja.spaincentral.cloudapp.azure.com
tlsSecret: motdepasseducertbeaucouptroplongmaissecuredeoufavecunarobasealafinmaispasvraimentparcequonapasledroitdelemettrealafin
grafana:
  service: kube-prometheus-stack-grafana
  port: 80
prometheus:
  service: kube-prometheus-stack-prometheus
  port: 9090
  path: /prometheus
alertmanager:
  service: kube-prometheus-stack-alertmanager
  port: 9093
  path: /alertmanager
